package fr.efrei.tp1.bo;

import java.io.Serializable;
import java.util.Comparator;

import androidx.annotation.NonNull;

//This class is used in order to represnt a User
final public class User
    implements Serializable
{

  //This class is used in order to sort a user
  public static final class UserComparator
      implements Comparator<User>
  {

    @Override
    public int compare(User o1, User o2)
    {
      return o1.name.compareTo(o2.name);
    }

  }

  @NonNull
  public final String name;



  public User(@NonNull String name)
  {
    this.name = name;

  }

  //The methods "equals" and "hashcode" has been
  //automatically generated by Android Studio
  //They are used in order to compare users (sort + deletion)
  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (!(o instanceof User))
    {
      return false;
    }

    User user = (User) o;

    if (!name.equals(user.name))
    {
      return false;
    }
  return false;
  }

  @Override
  public int hashCode()
  {
    int result = name.hashCode();

    return result;
  }
}
